# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sika' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sika
  pod 'SlideMenuControllerSwift'
  pod 'CarbonKit'
  pod 'AlamofireObjectMapper', '~> 4.0'  
  pod 'NVActivityIndicatorView'
  pod 'Firebase/Core'
  pod 'Firebase/Crash'

  target 'SikaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SikaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
